controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
contact:
    path: /contact
    controller: App\Controller\ContactController::showForm
contact_success:
    path: /contact/success
    controller: App\Controller\ContactController::success
follow:
    path: /follow
    controller: App\Controller\FollowsController::follow